apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
replicas:
- count: 4
  name: vote
namespace: prod
commonAnnotations:
  supported-by: sre@example.com
labels:
- includeSelectors: true
  pairs:
    env: prod
    project: instavote
patches:
- path: service.yaml
